---
all:
  children:
    kvm_hosts:
      hosts:
        main1:
          ansible_user: "{{ vm_user_name | default('ansible') }}"
          ansible_become_password: "{{ vault_become_password }}"
    rhel_vms:
      hosts:
        selinux-demo:
          ansible_host: 192.168.86.196
          ansible_user: "{{ vm_user_name | default('ansible') }}"
